---
- hosts: all
  remote_user: ansible
  become: yes
  become_method: sudo
  tasks:
  - name: Install epel-release
    yum: name=epel-release state=latest
    
  - name: Install pip
    yum: name=python-pip state=latest

  - name: install docker-py
    pip: name=docker-py

  - name: Running the container
    docker_container:
      image: harry452/hariwebapp:latest
      name: hariwebapp
      # path: docker
      state: started
      pull: yes
      ports:
        - 9000:8080

  - name: Check if container is running
    shell: docker ps
